#!/bin/bash
set +x

# This script installs DiscoverEd, adds some sample data, and runs a test search.
#
# For more information see <http://wiki.creativecommons.org/DiscoverEd_Quickstart>.
# --------------------------------------------------------

DISCOVER_ED_ROOT=./discovered
DED_BRANCH=jetty-included
# DED_DB_NAME=discovered

HTTP_PORT=8080
#TOMCAT_SERVER_PORT=8006
#TOMCAT_REDIRECT_PORT=8444

function die() {
    echo 
    echo "--- Error ---------------"
    numargs=$#
    for ((i=1; i <= numargs; i++)); do
        echo "$1"
        shift
    done
    echo "-------------------------"
    exit 1
}

# Make sure the target directory does not already exist
if [ -d "$DISCOVER_ED_ROOT" ]; then
    die "Oops, it looks like you already have a directory called $DISCOVER_ED_ROOT. To do a fresh install, move that directory, or remove it, then re-run this script."
fi

# check for dependencies
dependencies="nc ant git wc wget"
failed_dependencies=""
for dep in $dependencies; do
    which $dep > /dev/null || failed_dependencies="$failed_dependencies $dep"
done

# If this has exit code 1, then the port is closed
if nc -z localhost $HTTP_PORT; then
    die "To run this quickstart, you'll need to make port $HTTP_PORT available. Another process is using that port (possibly something previously launched by this script). You can also change the values of the HTTP_PORT variables in the script if you need."
fi

if [ "${failed_dependencies}" ]; then
    die "DiscoverEd requires the following missing dependencies:" "${failed_dependencies}" "You might be able to install this/these with a package manager like apt-get or yum."
fi

if [ -z $JAVA_HOME ]; then
    die "To run this script, you'll need to set the environment variable \$JAVA_HOME. This might work:" "   export JAVA_HOME=/usr/lib/jvm/java-6-sun/"
fi

JAVAC_LOCATION_HOPEFULLY="$JAVA_HOME/bin/javac"
if [ ! -f "$JAVAC_LOCATION_HOPEFULLY" ]; then
    die "Couldn't find a java compiler. Looked in $JAVAC_LOCATION_HOPEFULLY. Make sure your JAVA_HOME points to a Java Development Kit (JDK), not just a Java Runtime Environment (JRE)."
fi

### Okay, all the prerequisites are set. Now we can mkdir and move forward.

mkdir $DISCOVER_ED_ROOT
cd $DISCOVER_ED_ROOT

# Turn the root directory into an absolute pathname
DISCOVER_ED_ROOT=`pwd`



# Get the code
if [ -n "$1" ]; then
    git clone $1 src
else
    git clone git://gitorious.org/discovered/repo.git src
fi

cd src

git checkout $DED_BRANCH # make sure we are on the master branch, which should always be stable

# Build
ant -q # will take ~30 seconds

# update the configuration with our crawl directory
sed -i "s,CRAWL_DIR_LOCATION,$DISCOVER_ED_ROOT/crawl,g" conf/nutch-site.xml
sed -i "s,DERBY_DATABASE_PATH,$DISCOVER_ED_ROOT/db,g" conf/discovered.xml

# build the WAR file
ant war -q

# Add a curator
./bin/feeds addcurator "Notre Dame OpenCourseWare" http://ocw.nd.edu/

# Add a feed
./bin/feeds addfeed rss http://ocw.nd.edu/courselist/rss http://ocw.nd.edu/

# Check that all is well.
./bin/feeds listfeeds

# Do an aggregation
./bin/feeds aggregate

mkdir seed

# Create a seed file that Nutch can use when it crawls the web
./bin/feeds seed > seed/urls

echo "The seed file has this many lines:"
wc -l seed/urls

# Run the crawl using the seed we generated
./bin/nutch crawl seed -dir $DISCOVER_ED_ROOT/crawl -depth 1 

echo "We expect to see at least one hit for the string 'crime'"

# Query the search engine
./bin/nutch org.apache.nutch.searcher.NutchBean christianity

# Run with Jetty
cd $DISCOVER_ED_ROOT/src
ant -f dedbuild.xml serve &

WAIT=20
# Now, wait up to $WAIT seconds for Tomcat to start
for i in `seq 0 $WAIT`; do
    if nc -z localhost $HTTP_PORT; then
    	firefox "http://localhost:$HTTP_PORT/nutch-1.1/search.jsp?query=christianity"
        echo "Loaded a search for 'crime' in Firefox. This script will now exit."
        exit 0
    else
        sleep 1 # wait one second before retrying; because the loop is run $WAIT times, we wait that long
    fi
done

echo "Eek, Tomcat took more than $WAIT seconds to start. Try waiting a bit longer and visiting http://localhost:$HTTP_PORT/nutch-1.1/ in your web browser."
