#!/bin/bash
set +x

cd /tmp/

DED_DIR=/var/lib/discovered
MYSQL_ROOT_PASS="aewo4Fen"

# Move the old directory out of the way
if [ -d "$DED_DIR" ]; then
    echo "Oops, it looks like you already have a directory called $DED_DIR. To do a fresh install, move that directory, or remove it, then re-run this script."
    exit 1
fi

sudo mkdir $DED_DIR
sudo chown $USER $DED_DIR
cd $DED_DIR

# Get the code
if [ -n "$1" ]; then
    git clone $1 src
else
    git clone git://gitorious.org/discovered/repo.git src
fi

cd src

# Build
ant # will take ~30 seconds
ant war 

# Set up a database
echo 'DROP DATABASE IF EXISTS discovered; CREATE DATABASE discovered; GRANT ALL ON discovered.* TO discovered@localhost' | mysql -uroot -p"$MYSQL_ROOT_PASS"

# Add a curator
./bin/feeds addcurator "Notre Dame OpenCourseWare" http://ocw.nd.edu/

# Add a feed
./bin/feeds addfeed rss http://ocw.nd.edu/courselist/rss http://ocw.nd.edu/

# Check that all is well.
./bin/feeds listfeeds

# Do an aggregation
./bin/feeds aggregate

mkdir seed

# Create a seed file that Nutch can use when it crawls the web
./bin/feeds seed > seed/urls

echo "The seed file has this many lines:"
wc -l seed/urls

# For testing, let's try using nutch directly
#./bin/nutch crawl seed -dir crawl -depth 1 

./bin/nutch inject crawl/crawldb seed
./bin/nutch generate crawl/crawldb crawl/segments
./bin/nutch fetch crawl/segments/*
./bin/nutch updatedb crawl/crawldb crawl/segments/*
./bin/nutch invertlinks crawl/linkdb crawl/segments/*
./bin/nutch index crawl/indexes crawl/crawldb crawl/linkdb crawl/segments/*
./bin/nutch org.apache.nutch.searcher.NutchBean crime

#ant -f dedbuild.xml crawl

echo "We expect to see at least one hit for the string 'crime'"

# Query the search engine
./bin/nutch org.apache.nutch.searcher.NutchBean crime

cd ..

# Get tomcat, install it into this directory
wget http://mirror.olnevhost.net/pub/apache/tomcat/tomcat-6/v6.0.26/bin/apache-tomcat-6.0.26.tar.gz
tar xvf apache-tomcat*
cd apache-tomcat-6.0.26/

# Remove the default webapp
rm -rf webapps/ROOT

# Install our webapp
cp -v $DED_DIR/build/nutch*.war webapps/ROOT.war

# Start tomcat
bin/catalina.sh start

firefox "http://localhost:8080/search.jsp?query=crime"
